# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/daanv/Desktop/Git/PWM_controller_motor/PWM_Control/PWM_Control.srcs/sources_1/bd/Pwm_generator_zynq/ip/Pwm_generator_zynq_processing_system7_0_2/Pwm_generator_zynq_processing_system7_0_2.xci
# IP: The module: 'Pwm_generator_zynq_processing_system7_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/daanv/Desktop/Git/PWM_controller_motor/PWM_Control/PWM_Control.gen/sources_1/bd/Pwm_generator_zynq/ip/Pwm_generator_zynq_processing_system7_0_2/Pwm_generator_zynq_processing_system7_0_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'Pwm_generator_zynq_processing_system7_0_2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/daanv/Desktop/Git/PWM_controller_motor/PWM_Control/PWM_Control.srcs/sources_1/bd/Pwm_generator_zynq/ip/Pwm_generator_zynq_processing_system7_0_2/Pwm_generator_zynq_processing_system7_0_2.xci
# IP: The module: 'Pwm_generator_zynq_processing_system7_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/daanv/Desktop/Git/PWM_controller_motor/PWM_Control/PWM_Control.gen/sources_1/bd/Pwm_generator_zynq/ip/Pwm_generator_zynq_processing_system7_0_2/Pwm_generator_zynq_processing_system7_0_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'Pwm_generator_zynq_processing_system7_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
