# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/daanv/Desktop/Git/PWM_controller_motor/PWM_Control/PWM_Control.srcs/sources_1/bd/Complete_design_car/ip/Complete_design_car_PWM_Over_wrapper_0_1/Complete_design_car_PWM_Over_wrapper_0_1.xci
# IP: The module: 'Complete_design_car_PWM_Over_wrapper_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: C:/Users/daanv/Desktop/Git/PWM_controller_motor/PWM_Control/PWM_Control.srcs/sources_1/bd/PWM_Over/PWM_Over.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PWM_OVer || ORIG_REF_NAME==PWM_OVer} -quiet] -quiet

# IP: C:/Users/daanv/Desktop/Git/PWM_controller_motor/PWM_Control/PWM_Control.srcs/sources_1/bd/PWM_Over/ip/PWM_Over_Upcounter_0_1/PWM_Over_Upcounter_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PWM_Over_Upcounter_0_1 || ORIG_REF_NAME==PWM_Over_Upcounter_0_1} -quiet] -quiet

# IP: C:/Users/daanv/Desktop/Git/PWM_controller_motor/PWM_Control/PWM_Control.srcs/sources_1/bd/PWM_Over/ip/PWM_Over_Reg_0_2/PWM_Over_Reg_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PWM_Over_Reg_0_2 || ORIG_REF_NAME==PWM_Over_Reg_0_2} -quiet] -quiet

# IP: C:/Users/daanv/Desktop/Git/PWM_controller_motor/PWM_Control/PWM_Control.srcs/sources_1/bd/PWM_Over/ip/PWM_Over_DataChecker_0_1/PWM_Over_DataChecker_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PWM_Over_DataChecker_0_1 || ORIG_REF_NAME==PWM_Over_DataChecker_0_1} -quiet] -quiet

# IP: C:/Users/daanv/Desktop/Git/PWM_controller_motor/PWM_Control/PWM_Control.srcs/sources_1/bd/PWM_Over/ip/PWM_Over_Comparator_0_3/PWM_Over_Comparator_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PWM_Over_Comparator_0_3 || ORIG_REF_NAME==PWM_Over_Comparator_0_3} -quiet] -quiet

# IP: C:/Users/daanv/Desktop/Git/PWM_controller_motor/PWM_Control/PWM_Control.srcs/sources_1/bd/PWM_Over/ip/PWM_Over_Controller_0_1/PWM_Over_Controller_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PWM_Over_Controller_0_1 || ORIG_REF_NAME==PWM_Over_Controller_0_1} -quiet] -quiet

# XDC: c:/Users/daanv/Desktop/Git/PWM_controller_motor/PWM_Control/PWM_control.gen/sources_1/bd/PWM_Over/PWM_Over_ooc.xdc

# IP: C:/Users/daanv/Desktop/Git/PWM_controller_motor/PWM_Control/PWM_Control.srcs/sources_1/bd/Complete_design_car/ip/Complete_design_car_PWM_Over_wrapper_0_1/Complete_design_car_PWM_Over_wrapper_0_1.xci
# IP: The module: 'Complete_design_car_PWM_Over_wrapper_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: C:/Users/daanv/Desktop/Git/PWM_controller_motor/PWM_Control/PWM_Control.srcs/sources_1/bd/PWM_Over/PWM_Over.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PWM_OVer || ORIG_REF_NAME==PWM_OVer} -quiet] -quiet

# IP: C:/Users/daanv/Desktop/Git/PWM_controller_motor/PWM_Control/PWM_Control.srcs/sources_1/bd/PWM_Over/ip/PWM_Over_Upcounter_0_1/PWM_Over_Upcounter_0_1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PWM_Over_Upcounter_0_1 || ORIG_REF_NAME==PWM_Over_Upcounter_0_1} -quiet] -quiet

# IP: C:/Users/daanv/Desktop/Git/PWM_controller_motor/PWM_Control/PWM_Control.srcs/sources_1/bd/PWM_Over/ip/PWM_Over_Reg_0_2/PWM_Over_Reg_0_2.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PWM_Over_Reg_0_2 || ORIG_REF_NAME==PWM_Over_Reg_0_2} -quiet] -quiet

# IP: C:/Users/daanv/Desktop/Git/PWM_controller_motor/PWM_Control/PWM_Control.srcs/sources_1/bd/PWM_Over/ip/PWM_Over_DataChecker_0_1/PWM_Over_DataChecker_0_1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PWM_Over_DataChecker_0_1 || ORIG_REF_NAME==PWM_Over_DataChecker_0_1} -quiet] -quiet

# IP: C:/Users/daanv/Desktop/Git/PWM_controller_motor/PWM_Control/PWM_Control.srcs/sources_1/bd/PWM_Over/ip/PWM_Over_Comparator_0_3/PWM_Over_Comparator_0_3.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PWM_Over_Comparator_0_3 || ORIG_REF_NAME==PWM_Over_Comparator_0_3} -quiet] -quiet

# IP: C:/Users/daanv/Desktop/Git/PWM_controller_motor/PWM_Control/PWM_Control.srcs/sources_1/bd/PWM_Over/ip/PWM_Over_Controller_0_1/PWM_Over_Controller_0_1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PWM_Over_Controller_0_1 || ORIG_REF_NAME==PWM_Over_Controller_0_1} -quiet] -quiet

# XDC: c:/Users/daanv/Desktop/Git/PWM_controller_motor/PWM_Control/PWM_control.gen/sources_1/bd/PWM_Over/PWM_Over_ooc.xdc
