# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/daanv/Desktop/Git/PWM_controller_motor/PWM_Control/PWM_Control.srcs/sources_1/bd/Complete_design_car/ip/Complete_design_car_processing_system7_0_0/Complete_design_car_processing_system7_0_0.xci
# IP: The module: 'Complete_design_car_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/daanv/Desktop/Git/PWM_controller_motor/PWM_Control/PWM_Control.gen/sources_1/bd/Complete_design_car/ip/Complete_design_car_processing_system7_0_0/Complete_design_car_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Complete_design_car_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/daanv/Desktop/Git/PWM_controller_motor/PWM_Control/PWM_Control.srcs/sources_1/bd/Complete_design_car/ip/Complete_design_car_processing_system7_0_0/Complete_design_car_processing_system7_0_0.xci
# IP: The module: 'Complete_design_car_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/daanv/Desktop/Git/PWM_controller_motor/PWM_Control/PWM_Control.gen/sources_1/bd/Complete_design_car/ip/Complete_design_car_processing_system7_0_0/Complete_design_car_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Complete_design_car_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
